### ISSUE TITLE
It will break on IE because of unsupported Object.assign

### ISSUE THREAD

**Issue by devenbhooshan** [zendesk/zopim-chat-web-sdk-sample-app#10]
This sample web-sdk gave  `Object doesn't support property or method 'assign'` on IE. We resolved it using this [polyfill](https://github.com/rubennorte/es6-object-assign).

**Comment by rd1992** [comment]
Hi @devenbhooshan ,

Thank you for bringing this to our attention. The sample code has not been tested for all browsers as it is meant to serve as a starting point for development using the web sdk. The web sdk itself is compatible with IE 9 and above.

Best,
Rajan
