### ISSUE TITLE
Department gets overwritten

### ISSUE THREAD

**Issue by jkilesc** [zendesk/zopim-chat-web-sdk-sample-app#13]
Departments in the store gets overwritten everytime department_update event is fired

You need to change ChatStore.js to something like this
```
 const DEFAULT_STATE = {
        connection: 'closed',
        account_status: 'offline',
-       departments: [],
+       departments: {},
        visitor: {},
        agents: {},
        chats: SortedMap(),
@@ -29,9 +29,9 @@ function update(state = DEFAULT_STATE, action) {
                                account_status: action.detail
                        };
                case 'department_update':
+                       state.departments[action.detail.id] = action.detail;
                        return {
-                               ...state,
-                               departments: action.detail
+                               ...state
                        };
```

**Comment by ngfreemantleShine** [comment]
I came across this problem too, and solved it in a similar fashion.
@jkilesc or @junyi, do either of you know how to actually assign a chat to a department? In reference to the web-sdk api methods, I can't seem to find a method which actually initiates a chat and assigns a client to the specified department.
Any ideas?

**Comment by jkilesc** [comment]
@ngfreemantle https://api.zopim.com/web-sdk/#zchat-setvisitordefaultdepartment-id-callback

**Comment by ngfreemantleShine** [comment]
Ahh of course. I misread the "..will only take effect on the next chat." Thanks! @jkilesc

**Comment by nkeatjb** [comment]
fyi we don't use departments :)

**Comment by junyi** [comment]
Hi all,

This should be fixed as of the latest master in https://github.com/zopim/chat-web-sdk-sample-app/commit/4753949e98a6328230390f39e22fc2df9b50a3a9.

Thanks for reporting this @jkilesc!
