### ISSUE TITLE
unique “key” prop warning occurs when trigger message is sent

### ISSUE THREAD

**Issue by ynarish** [zendesk/zopim-chat-web-sdk-sample-app#15]
I'm getting warning:
> Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `MessageList`. See https://fb.me/react-warning-keys for more information.
>     in div (created by MessageList)
>     in MessageList (created by App)
>     in div (created by App)
>     in div (created by App)
>     in App (created by Connect(App))
>     in Connect(App)
>     in Provider

It occurs when trigger message is sent. Then I refresh the page, no warning is displayed.  I suppose it occurs when 'typing' event and 'chat.memberjoin' event occured sequentially.

**Comment by ramirogm** [comment]
That's probably because it's using a timestamp as the key.
You can use any unique identifier to avoid this error

**Comment by ynarish** [comment]
OK. I'll try it. thanks.

**Comment by junyi** [comment]
Hi @ynarish, apologies for the late reply, this should be fixed in the latest master already.
