### ISSUE TITLE
Is there any way to create a new chat on the server side based on the user login info?

### ISSUE THREAD

**Issue by ramirogm** [zendesk/zopim-chat-web-sdk-sample-app#16]
Hi. I see that the login form data is used to change the visitor information, but this is not used to identify the user on the server chat side. That is, if I identify as user "user1", chat a little, then refresh the page and identify as "user3", both "sessions" go to the same chat history and support ticket.

**Comment by rshokrizadeh** [comment]
Hey @ramirogm,

Noticed you posted the same question here: https://chat.zendesk.com/hc/en-us/articles/115000741447?page=1#comment_115001973787

Will answer there and close this issue.

Thanks,
Ramin
