### ISSUE TITLE
Illegal Web SDK error on connection

### ISSUE THREAD

**Issue by johanhenriksson** [zendesk/zopim-chat-web-sdk-sample-app#24]
The web sdk seems broken somehow. The web socket is immediately closed, returning an "illegal_web_sdk" error which is not documented anywhere.

I've tried the 3 latest versions of the SDK but none of them work.

Is the SDK still supported?

**Comment by tgohn** [comment]
Hi @johanhenriksson 

Apologize for the confusion.
`illegal_web_sdk` is an error returned when your Zendesk Chat account does not have this feature enabled.

To use the Web SDK, you will need a Zendesk Chat account on the Enterprise or Premium (Legacy) package.
You can also sign up for a new Chat trial account to try out and evaluate the feature. The signup link 
is located [here](https://www.zendesk.com/register/chat/)

Hope this helps 🙂

**Comment by johanhenriksson** [comment]
Oh. Well that's disappointing

Closing the issue then. Thanks
