### ISSUE TITLE
getOperatingHours() always returns "undefined"

### ISSUE THREAD

**Issue by mathiastm** [zendesk/zopim-chat-web-sdk-sample-app#26]
Hi,
I'm trying desperately to get the operating hours via the getOperatingHours() function of your SDK [https://api.zopim.com/web-sdk/#zchat-getoperatinghours.](https://api.zopim.com/web-sdk/#zchat-getoperatinghours) I set in "Parameter => Account => business hours" the schedule and I saved my changes. However the function always returns "undefined". Is there something I missed?

**Comment by rshokrizadeh** [comment]
Hi @mathiastm,

Thanks for posting your question. Since we will need account information to check your operating hours configuration, it is best you email support@zendesk.com to get further assistance since the problem is not with the sample code itself.

Cheers,
Ramin

**Comment by mathiastm** [comment]
ok thx.
