### ISSUE TITLE
Concierge info

### ISSUE THREAD

**Issue by mathiastm** [zendesk/zopim-chat-web-sdk-sample-app#27]
Hi,
Is there a way to get concierge's informations (image/slogan ...) ?

Mathias

**Comment by rshokrizadeh** [comment]
@mathiastm there is an API to get serving agent info: https://api.zopim.com/web-sdk/#zchat-getservingagentsinfo

If you want to create something similar to concierge (when no agent is in the chat), it will require your own custom code.
