### ISSUE TITLE
Web SDK not suitable for React Native

### ISSUE THREAD

**Issue by aiavci** [zendesk/zopim-chat-web-sdk-sample-app#31]
**Issue summary**
This sample is for React projects. The web-sdk only works for browsers and is heavily opinionated. There are references to `window`, `navigator`, `document` and `document.createElement` calls.

**Request**
Could the SDK be built with no reference to any browser specific items?

Is it open source?

**Comment by rshokrizadeh** [comment]
Hi @aiavci , the Web SDK itself is not open sourced by this repo with the sample React implementation is open sourced. 

What you are asking for is not something the Web SDK will be solving for since it assumes the traffic is coming from web browsers.
