### ISSUE TITLE
Chat room does not load

### ISSUE THREAD

**Issue by jonathan-dc** [zendesk/zopim-chat-web-sdk-sample-app#33]
Hello,

I configured the widget with my account key, the load page, the chat button too, but when I click on it the chat window goes up well but then there is a load with a small blue circle which gets bigger and it never stops.

And when I compile, and I host the file on the site, even the chat button does not load.

Thank you in advance,
cordially

**Comment by rshokrizadeh** [comment]
Hi @jonathan-dc , can you provide your account key and the test page with the code? The sample code is working for me, so I am wondering if your account is not on the required Enterprise/Premium plan.

**Comment by RussellRansom** [comment]
+1 to this issue. Account key I'm trying is Enterprise.

Looks like the web socket connection times out after 10 seconds and closes.

**Comment by RussellRansom** [comment]
-1 to this issue. I had Widget Security Enabled in Zendesk. Whoops!

**Comment by kingisaac95** [comment]
I'm having the same issue @rshokrizadeh, any updates on this?

**Comment by rshokrizadeh** [comment]
@kingisaac95 please email support@zendesk.com with your account key, page with the deployment and the advocacy team will help you troubleshoot the problem you are experiencing.

**Comment by kingisaac95** [comment]
@rshokrizadeh I've opened a ticket but haven't heard back.

**Comment by rshokrizadeh** [comment]
@kingisaac95  The support team response time on tickets is more than one day. Please be patient and a member of the advocacy team will reach out to you on the ticket. There are no known issue with the Web SDK or sample code, so it is most probably something specific to your custom code or account configuration.
