### ISSUE TITLE
sendChatRating gives invalid response

### ISSUE THREAD

**Issue by drmovi** [zendesk/zopim-chat-web-sdk-sample-app#38]
when use `zChat.sendChatRating('good'); ` it gives 400 error code invalid message

**Comment by mustafaezer** [comment]
The documentation says that:

> Once again, ensure that you only allow the visitor to rate or comment while a chat session is still active.

Could you make sure that you are trying the rate the chat in terms of the business rules that the documentation guided? Maybe considering passing a response/error handler callback function to the `sendChatRating` might be another option for the resolve to issue with more detail/knowledge on the hand.
