### ISSUE TITLE
Compile Normal Widget

### ISSUE THREAD

**Issue by nkeat12** [zendesk/zopim-chat-web-sdk-sample-app#4]
When I run npm run dist and place the new widget.js on my site it always shows the docked version.

I dont see anything in the docs in terms of a config option that will compile the normal version. 

How can I accomplish this?

**Comment by junyi** [comment]
Hi @nkeat12,

You can change the value at https://github.com/zopim/chat-web-sdk-sample-app/blob/master/src/components/Widget.js#L24 to `normal`. This should compile it to the normal version.

Hope this helps.

Thanks,
Jun Yi

**Comment by nkeatjb** [comment]
It changes the default when you run it on local server via NPM start, but when you run the npm run dist and then take the compiled widget.js it compiles the docked version.

**Comment by nkeatjb** [comment]
This is output in console after changing the line you mentioned — the new compiled widget.js still defaults to docked style. https://gist.github.com/nkeatjb/0bd55162202054be4d5e05ad9e7360d9

**Comment by junyi** [comment]
Hi @nkeatjb,

Thanks for pointing this out.

We have noticed that there was a bug previously in the code and have refactored it such that the theme can now be changed via the config file. You may refer to https://github.com/zopim/chat-web-sdk-sample-app/blob/master/src/config/base.js#L7 on how to change the theme between docked and normal.

Thanks 🙂 

Regards,
Jun Yi

**Comment by nkeatjb** [comment]
One more issue — when it compiles, it automatically shows the form even if the agent is online and there is no submit button. 

<img width="314" alt="screen shot 2017-02-03 at 11 23 57 am" src="https://cloud.githubusercontent.com/assets/24721822/22605126/61e605a0-ea03-11e6-9e4b-8723a641921d.png">

**Comment by nkeatjb** [comment]
also that new config option still not working after compiling!

**Comment by junyi** [comment]
Hi @nkeatjb,

> One more issue — when it compiles, it automatically shows the form even if the agent is online

The form that you are seeing is meant to demonstrate pre-chat form, which is present in the standalone widget, and used to request for a visitor's information before the chat is started.

Feel free to fork this repository and modify the code as necessary if you have other requirements, as this repository only serves to provide a demonstration of what can be done with the Zendesk Chat Web SDK. Please also note that in no way is this sample app a replacement of the original widget.

> there is no submit button.

For the missing submit button, I am not sure if how you are encountering the issue as this sample app has not been tested on all browsers and platforms to ensure compatibility.

> also that new config option still not working after compiling!

I suspect that you might have forgotten to run `git pull` to update your local copy of this repository. You might also need to clear your local storage after recompiling the code.

Hope this helps,
Jun Yi
