### ISSUE TITLE
Add Rating option to chat

### ISSUE THREAD

**Issue by nkeatjb** [zendesk/zopim-chat-web-sdk-sample-app#5]
I dont see any documentation in the developer docs that references how to add the agent rating option to this sample app. Is there something i'm missing? Thanks!

I have attached the standard Zendesk chat widget rating for reference. 

![screen shot 2017-02-06 at 11 23 24 am](https://cloud.githubusercontent.com/assets/24721822/22662652/9bf626a0-ec5e-11e6-8bff-9bf1e663e6e4.png)

**Comment by nkeatjb** [comment]
also when the agent requests a rating via the agent interface there is a bug

![screen shot 2017-02-06 at 11 32 37 am](https://cloud.githubusercontent.com/assets/24721822/22663020/eba120be-ec5f-11e6-9e23-451073a7aeff.png)

**Comment by junyi** [comment]
Hi @nkeatjb,

> I dont see any documentation in the developer docs that references how to add the agent rating option to this sample app. Is there something i'm missing? Thanks!

You can make use of the [`sendChatRating`](https://api.zopim.com/web-sdk/#zchat-sendchatrating-rating-callback) API to allow the visitors to send satisfaction ratings for the agents.

> also when the agent requests a rating via the agent interface there is a bug

As mentioned in the previous issue https://github.com/zopim/chat-web-sdk-sample-app/issues/4#issuecomment-277879405, the sample widget is only a demonstration of the Web SDK and is never meant to be feature complete. You are encouraged to extend it by implementing other features on your own as you see fit if you intend to use this repository as a foundation.

Regards,
Jun Yi

**Comment by batjo** [comment]
Would it be possible to make the sample app at least feature complete? This sample widget looks already so much better than the previous one that I don't even want to use that anymore. By adding all features from the previous chat system, users don't have to reinvent how to show ratings for example.

Stating that each of your customers should add this by himself makes no sense to me. I guess most people are just looking to change the layout and CSS of the widget. So by providing a feature complete example you would help them a lot.

**Comment by nkeatjb** [comment]
Totally agree @risp — great to have a sample app but it has bugs (e.g when agents request ratings) and lacks basic functionality such as the built in ratings feature. Documentation is not complete on adding those features either.

**Comment by nkeatjb** [comment]
@junyi is there anywhere the standard zendesk chat widget code is available so we can look at how that functions? Understand the sendChatRating API call, but need to add the Agent tagline ETC. 

Would be immensely helpful to have some sort of functioning code to look at as the documentation does not address these issues. 

<img width="359" alt="screen shot 2017-02-14 at 9 50 18 am" src="https://cloud.githubusercontent.com/assets/24721822/22941586/efd39da6-f29a-11e6-9907-58e547d2753f.png">

**Comment by hxinen** [comment]
I agree. Too bad we didn't get a reply even after 5 months.
