### ISSUE TITLE
Triggers are not shown

### ISSUE THREAD

**Issue by batjo** [zendesk/zopim-chat-web-sdk-sample-app#6]
I have a couple of triggers and those are not shown when using this new widget. It would be really nice if the button would have a badge icon with the number of unread messages, and when clicking on the the badge clears. Would it be possible to add this to the sample?

If not could you maybe point me in the right direction to open the chat window when a chat message (from an agent or trigger) arrives?

**Comment by tgohn** [comment]
hi @risp 

Thank you for your feedback.

This sample app was created as an inspiration/demonstration of how we can make use of Zendesk Chat SDK to create a customized chat experience.

With the idea of showing chat window by default on new agent/trigger message,
we could do the following:
- remember the timestamp when chat window was minimized
- check for timestamp of new agent/trigger messages
- if new message's timestamp is greater than chat window minimized timestamp, we maximize the chat window

Here is a quick implementation of the above https://github.com/tgohn/chat-web-sdk-sample-app/commit/af0f5afb57c60bdb014e934d38dfa44249e9fb35

Hope this helps :)

**Comment by batjo** [comment]
Thanks that works really great!
