### ISSUE TITLE
Identify Visitors 

### ISSUE THREAD

**Issue by nkeatjb** [zendesk/zopim-chat-web-sdk-sample-app#7]
We are trying to identify our logged in visitors via a simple script and push their credentials into Zendesk Chat — the following script works fine with the standard zendesk widget but when testing with this React app we are getting an error in console:

Uncaught ReferenceError: zChat is not defined
    at HTMLDocument.<anonymous> ((index):1162)
    at o (jquery.js:1)
    at Object.fireWith (jquery.js:1)
    at Function.ready (jquery.js:1)
    at HTMLDocument.B (jquery.js:1)

Script that previously worked

`<script>
function zendeskChatIdentify()
{
	var customerData = storageGetValue(customerLocalStorage);
	if( customerData ){
		/*$zopim(function() {
			$zopim.livechat.setName(customerData.full_name);
			$zopim.livechat.setEmail(customerData.email);
			if(customerData.phone) $zopim.livechat.setPhone(customerData.phone);
		});*/
		
	}
}
$(document).ready(function(e) {
	//if( typeof zendeskChatIdentify!=='undefined' ) zendeskChatIdentify();
	zChat.init({
		account_key: 'account_key',
		suppress_console_error : true
	});
	
});
</script>`

**Comment by rshok** [comment]
Hi @nkeatjb,

The Web SDK does not support the standalone widget Javascript APIs, you will need to use the [Web SDK specific API](https://api.zopim.com/web-sdk/#zchat-setvisitorinfo-options-callback) to fill out the visitor information.

Thanks,
Ramin
