### ISSUE TITLE
Test Example

### ISSUE THREAD

**Issue by jgrahamthomas** [zendesk/zopim-chat-web-sdk-sample-app#8]
Hey guys,

This is a great reference project. We're building a React-based frontend on top of the Web SDK (but using a different store library). I'd love to see testing examples thrown into this project, as this might give me a better sense of how to stub/mock the WebSDK for our own testing purposes.

Again, thanks for this reference project. It has been a big help.

**Comment by tgohn** [comment]
Hi @jgrahamthomas,                                                                 
                                                                                   
Thank you for your question.                                                       
                                                                                   
For the WebSDK exposed `zChat`, it behaves kind of like an EventEmitter with methods named `.on()` and `.fire()`.
                                                                                   
So if the UI is listening for chat event like [this](https://github.com/zopim/chat-web-sdk-sample-app/blob/master/src/components/Widget.js#L58), we can control the UI by faking the zChat's [events](https://api.zopim.com/web-sdk/#events).
For other methods of zChat, we can probablly use [sinon.js](http://sinonjs.org/releases/v1.17.7/) for mock/stub.
                                                                                   
For example, to trigger connected state of the UI:                                           
```js                                                                              
sinon.stub(zChat, 'getConnectionStatus').returns('connected')                      
zChat.fire('connection_update', 'connected')                                       
```                                                                                
                                                                                
Hope this helps :)

**Comment by jgrahamthomas** [comment]
Much appreciated. I ended up "mocking" `zChat` with an `EventEmitter`, and adding requisite functions (such as `init()`) to the prototype. But I might try your approach instead.
