### ISSUE TITLE
Collections breaks Array.prototype.find

### ISSUE THREAD

**Issue by jkilesc** [zendesk/zopim-chat-web-sdk-sample-app#9]
This widget will break Array.prototype.find in any project its included into because of this shim in collections

https://github.com/montagejs/collections/issues/165
https://github.com/montagejs/collections/issues/182
https://github.com/montagejs/collections/issues/178

It also breaks Array.prototype.from
https://github.com/montagejs/collections/issues/169

And the crypto library
https://github.com/montagejs/collections/issues/162

**Comment by jkilesc** [comment]
I fixed mine by downgrading collections to version 2.0.2

**Comment by tgohn** [comment]
Hi @jkilesc 

Appreciate  the detailed bug report and the work around. 🙇 
We'll work on this and see what we can do.

**Comment by rd1992** [comment]
Hi @jkilesc 

Thank you for bringing this bug to our attention. We have updated the `package.json` to use version 2 of `collections` module. Will update the module once its fixed upstream.

Thanks,
Rajan
